In [20]:
import sys

numbers = [1, 2, 3, 4]
print(sys.getsizeof(numbers))
print(numbers)

120
[1, 2, 3, 4]


Looks similar.

But internally completely different.

4️⃣ What Makes NumPy Different?

NumPy array:

Stores data in contiguous memory block
All elements are same type (homogeneous)
No Python object overhead per element
Implemented in C

Memory looks like:

[1][2][3][4]

One continuous block.

That means:

Faster computation
Less memory usage
CPU vectorization possible

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(sys.getsizeof(arr))
print(arr)

120
[1 2 3 4]


In [21]:
#performance
import time

lst = list(range(1000000))

start = time.time()
result = [x * 2 for x in lst]
end = time.time()

print("List time:", end - start)

List time: 0.09435915946960449


In [22]:
import numpy as np
import time

arr = np.arange(1000000)

start = time.time()
result = arr * 2
end = time.time()

print("NumPy time:", end - start)

NumPy time: 0.017133235931396484


In [ ]:
import numpy as np
arr1=np.array([10,20,30,"Sun"])
print(arr1)

In [4]:
np.array([])


array([], dtype=float64)

In [2]:
import numpy as np
arr1=np.array([10,20,30])
print(arr1)

[10 20 30]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("Array:", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)

# Understand each:

# shape → structure
# ndim → how many axes
# dtype → type of elements
# size → total elements

Array: [10 20 30 40]
Shape: (4,)
Dimensions: 1
Data type: int32
Size: 4


In [ ]:
arr = np.arange(0, 10, 2) #start,stop,step
print(arr)

[0 2 4 6 8]


In [11]:
salary=np.array([20000,30000,40000])
bonus=salary*1.10
print(bonus)
salary_reshaped = salary.reshape(-1, 1)
print(salary_reshaped)
experience = np.array([1, 3, 5]).reshape(3,1)
print(experience)
combined = np.hstack((salary_reshaped, experience))
print(combined)

[22000. 33000. 44000.]
[[20000]
 [30000]
 [40000]]
[[1]
 [3]
 [5]]
[[20000     1]
 [30000     3]
 [40000     5]]


In [12]:
import numpy as np
salary = np.array([20000, 30000, 40000])

# add bonus 10%
# reshape
# combine with experience

salary_update = salary * 1.10

salary_update = salary_update.reshape(-1,1)

experience = np.array([1,3,5]).reshape(-1,1)

dataset = np.hstack((salary_update, experience))
dataset = dataset.astype(int)
#np.set_printoptions(suppress=True)
print(dataset)

[[22000     1]
 [33000     3]
 [44000     5]]


In [13]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

expanded = np.expand_dims(data, axis=1)
print(expanded)
print(expanded.shape)

[[[10 20 30]]

 [[40 50 60]]]
(2, 1, 3)


In [14]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

expanded = np.expand_dims(data, axis=0)
print(expanded)
print(expanded.shape)

[[[10 20 30]
  [40 50 60]]]
(1, 2, 3)


age = [25, 30, 35, 40]
salary = [40000, 50000, 60000, 70000]
experience = [2,5,7,10]

#1. convert all into numpy arrays
#2. convert all arrays into column format
#3. cobine all feature into a datset
#4. increase all salaries by 10%
#5. Normalize salary (divide my max salary)
#6. Extract all ages, first employee record
#7. calculate mean salary, median experience and std dev of age
#8. iterate through dataset and print each row

In [15]:
import numpy as np

age = np.array([25, 30, 35, 40])
salary = np.array([40000, 50000, 60000, 70000])
experience = np.array([2, 5, 7, 10])


age = age.reshape(-1, 1)         
salary = salary.reshape(-1, 1)   
experience = experience.reshape(-1, 1)


dataset = np.hstack((age, salary, experience))  
print("Final Dataset:\n", dataset)


salary_updated = salary * 1.10   # vectorized
print("\nUpdated Salary:\n", salary_updated)


max_salary = np.max(salary_updated)
salary_normalized = salary_updated / max_salary  
# broadcasting: each value divided by max
print("\nNormalized Salary:\n", salary_normalized)


print("\nAll Ages:", dataset[:, 0])
print("\nFirst Employee:", dataset[0])


print("\nMean Salary:", np.mean(salary))
print("Median Experience:", np.median(experience))  
print("Std Age:", np.std(age))  


print("\nIterating through dataset:")
for row in dataset: 
    print(row)

Final Dataset:
 [[   25 40000     2]
 [   30 50000     5]
 [   35 60000     7]
 [   40 70000    10]]

Updated Salary:
 [[44000.]
 [55000.]
 [66000.]
 [77000.]]

Normalized Salary:
 [[0.57142857]
 [0.71428571]
 [0.85714286]
 [1.        ]]

All Ages: [25 30 35 40]

First Employee: [   25 40000     2]

Mean Salary: 55000.0
Median Experience: 6.0
Std Age: 5.5901699437494745

Iterating through dataset:
[   25 40000     2]
[   30 50000     5]
[   35 60000     7]
[   40 70000    10]
