In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures
from statistics import mode
from scipy.stats import binom
from scipy.stats import norm
from scipy.stats import ttest_rel

# Question 1:

In [15]:
X = np.array([1, 2, 3, 4, 5], dtype=float)
X=X.reshape(-1,1)
print(X)
y = np.array([35, 45, 50, 65, 70], dtype=float)
print(y)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[35. 45. 50. 65. 70.]


In [16]:
model=LinearRegression()


In [17]:
model.fit(X,y)

LinearRegression()

In [21]:
slope=model.coef_
print(slope)
intercept=model.intercept_
print(intercept)

[9.]
26.0


In [27]:
pred=model.predict([[6]])
print(pred)

[80.]


# Question 2

In [28]:
data={
    'Area':[1000,1500,1800,2200,2500],
    'Bedrooms':[2,3,3,4,4,],
    'Price':[50,65,72,85,95]
}
df=pd.DataFrame(data)
print(df)

   Area  Bedrooms  Price
0  1000         2     50
1  1500         3     65
2  1800         3     72
3  2200         4     85
4  2500         4     95


In [34]:
X=df[['Area','Bedrooms']]
print(X)


   Area  Bedrooms
0  1000         2
1  1500         3
2  1800         3
3  2200         4
4  2500         4


In [ ]:
Y=df['Price']
print(Y)

0    50
1    65
2    72
3    85
4    95
Name: Price, dtype: int64


In [42]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)


In [43]:
model=LinearRegression()

In [44]:
model.fit(X_train,Y_train)

LinearRegression()

In [45]:
y_pred=model.predict(X_test)
print(y_pred)

[65.25 91.75]


In [46]:
print("Coefficients:",model.coef_)

print("Intercept:",model.intercept_)

print("MSE:",mean_squared_error(Y_test,y_pred))

print("R2:",r2_score(Y_test,y_pred))

Coefficients: [0.0225 4.    ]
Intercept: 19.500000000000007
MSE: 5.3125
R2: 0.9763888888888889


In [48]:
new_house=[[2000,3]]

print("Predicted Price:",model.predict(new_house))

Predicted Price: [76.5]


c:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


# Question 3

In [49]:
X=np.array([1,2,3,4,5])
X=X.reshape(-1,1)
print(X)
y = np.array([2, 8, 18, 32, 50])

[[1]
 [2]
 [3]
 [4]
 [5]]


In [51]:
poly = PolynomialFeatures(degree=2)

X_poly = poly.fit_transform(X)

In [52]:
print(X_poly)

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


In [53]:
model = LinearRegression()

model.fit(X_poly, y)

LinearRegression()

In [54]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 0.0
Coefficients: [ 0.00000000e+00 -1.70974346e-14  2.00000000e+00]


In [57]:
y_pred=model.predict(X_poly)
print(y_pred)

[ 2.  8. 18. 32. 50.]


In [58]:
print("Coefficients:",model.coef_)

print("Intercept:",model.intercept_)

print("MSE:",mean_squared_error(y,y_pred))

print("R2:",r2_score(y,y_pred))

Coefficients: [ 0.00000000e+00 -1.70974346e-14  2.00000000e+00]
Intercept: 0.0
MSE: 2.6743370763123826e-28
R2: 1.0


In [55]:
X_new = poly.transform([[6]])

prediction = model.predict(X_new)

print(prediction)

[72.]


# Question 4

In [59]:
data = {
    'X1': [0,3,6,9,12,15,18,21,24,27,30,33,36,39,42],
    'X2': [1,4,7,10,13,16,19,22,25,28,31,34,37,40,43],
    'X3': [2,5,8,11,14,17,20,23,26,29,32,35,38,41,44],
    'y' : [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]
}

df = pd.DataFrame(data)
print(df)

    X1  X2  X3   y
0    0   1   2   0
1    3   4   5   1
2    6   7   8   2
3    9  10  11   3
4   12  13  14   4
5   15  16  17   5
6   18  19  20   6
7   21  22  23   7
8   24  25  26   8
9   27  28  29   9
10  30  31  32  10
11  33  34  35  11
12  36  37  38  12
13  39  40  41  13
14  42  43  44  14


In [62]:
X=df[['X1','X2','X3']]
#X=X.reshape(-1,1)
print(X)
y=df['y']
print(y)

    X1  X2  X3
0    0   1   2
1    3   4   5
2    6   7   8
3    9  10  11
4   12  13  14
5   15  16  17
6   18  19  20
7   21  22  23
8   24  25  26
9   27  28  29
10  30  31  32
11  33  34  35
12  36  37  38
13  39  40  41
14  42  43  44
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
Name: y, dtype: int64


In [64]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

In [67]:
print("Training samples:",len(X_train))

print("Test samples:",len(X_test))

print("Shape of X_train:",X_train.shape)

Training samples: 12
Test samples: 3
Shape of X_train: (12, 3)


# Question 5

In [ ]:
ages = np.array([12, 15, 14, 10, 18, 20, 14, 16, 15, 22])
print("Mean:", np.mean(ages))
print("Median:", np.median(ages))
print("Mode:", mode(ages))
print("Variance:", np.var(ages))
print("Standard Deviation:", np.std(ages))

Mean: 15.6
Median: 15.0
Mode: 15
Variance: 11.64
Standard Deviation: 3.411744421846396


# Question 6

In [78]:
scores = np.array([45, 50, 55, 60, 65, 70, 75])
mean = np.mean(scores)
std = np.std(scores)      
z_score = (75 - mean) / std
print("Mean:", mean)
print("Standard Deviation:", std)
print("Z-score of 75:", z_score)
if abs(z_score) > 2:
    print("75 is an Outlier")
else:
    print("75 is NOT an Outlier beacuse it is less than 2")

Mean: 60.0
Standard Deviation: 10.0
Z-score of 75: 1.5
75 is NOT an Outlier beacuse it is less than 2


# Question 7

In [79]:
advertising = np.array([200, 250, 300, 350, 400])
sales = np.array([20, 24, 27, 33, 38])
correlation = np.corrcoef(advertising, sales)
print(correlation)
print("Pearson Correlation Coefficient:", correlation[0,1])

[[1.         0.99339927]
 [0.99339927 1.        ]]
Pearson Correlation Coefficient: 0.9933992677987827


# Question 8

In [ ]:
n = 8
p = 0.1
x = 2
probability = binom.pmf(x, n, p)
print("Probability:", probability)

# Question 9

In [83]:
mean = 70
std = 8
prob_between = norm.cdf(78, mean, std) - norm.cdf(62, mean, std)
prob_above = 1 - norm.cdf(86, mean, std)
print("Between 62 and 78:", prob_between)
print("Above 86:", prob_above)

Between 62 and 78: 0.6826894921370859
Above 86: 0.02275013194817921


# Question 10

In [88]:
before = np.array([70, 72, 68, 75, 74])
after = np.array([78, 80, 76, 82, 79])
alpha = 0.05
t_statistic, p_value = ttest_rel(after, before)
print("T-statistic:",t_statistic)
print("P-value:",p_value)
if p_value < alpha:
    print("Reject the Null Hypothesis")
else:
    print("Fail to Reject the Null Hypothesis")

T-statistic: 12.347898130260639
P-value: 0.00024718640163122284
Reject the Null Hypothesis
